### ISSUE TITLE
Verify iTunes Receipt failed.

### ISSUE THREAD

**Issue by googollee** [fullsailor/pkcs7#9]
For background, [iTunes Receipt](https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW10) is purchased receipt in iTunes(macOS/iOS). It's a binary file which encoded with pkcs#7.

I try to use this package to parse iTunes Receipt like:

```go
b, err := ioutil.ReadFile("./test_receipt")

d, err := base64.StdEncoding.DecodeString(string(b))

pkcs, err := pkcs7.Parse(d)

pkcs.Verify()
```

And it always return `crypto/rsa: verification error` when verify. Even I can parse data with pkcs.Content through asn1.

I can verify the file with openssl OK.

Is there anything I'm wrong or missing when verifying?

Attached test file: [test_receipt.zip](https://github.com/fullsailor/pkcs7/files/380123/test_receipt.zip)

**Comment by fullsailor** [comment]
Hey, looks like you're doing everything right. I was able to reproduce the issue using your sample receipt.

It looks like we don't handle cases where the AuthenticatedAttributes are omitted from the signature. Simple enough to fix. 

Thanks for the report!

**Comment by fullsailor** [comment]
@googollee I had to push a quick fix since I missed a hunk in the git commit. If you tried it out before the last 5 minutes or so, try again now.

Side note, I've now setup Travis CI to prevent this in the future.

**Comment by googollee** [comment]
Great. Thank you for quick fix. I just try and it's works now.
